apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-10gi
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.39
    path: "/volume1/cluster/grafana"

