apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: '3000'
spec:
  type: NodePort
  selector:
    component: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
