apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      volumes:
        - name: prometheus-volume-config
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-volume-root
          persistentVolumeClaim:
            claimName: prometheus-pvc
      containers:
        - name: prometheus
          image: prom/prometheus:v2.23.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-volume-config
              mountPath: /etc/prometheus/
            - name: prometheus-volume-root
              mountPath: /prometheus/
